# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3yotjkksNhTnDT4cM-4s9MbOzMnZQeC
"""

import streamlit as st

# Set the title of the webpage
st.title("New Mexico Water Crisis")

# Create a box with some information
st.info("This is a critical issue affecting the state of New Mexico.")

# Display an image from a URL
image_url = https://urbanaffairsassociation.org/wp-content/uploads/2024/09/standard.png
st.image(image_url, caption="Water resources in New Mexico", use_column_width=True)